config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'forum/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :materials do
    collection do
      get :download
    end
  end

  get '/ad/index'
  get '/contact' => 'ads#contact'

  resources :ads
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'home#index'

  get '/material/questionpaper'
  get '/material/notes'
  get '/material/semnotes'

  post '/remove_profile_pic'=>'profile#remove_profile_pic'
  post 'forum/question'
  post 'forum/answer'
  get 'forum/answer/:id' => 'forum#show_answer'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  ratyrate_rateable 'rating'
  belongs_to :user

end

app/models/ad_contact_worker.rb
class AdContactWorker

	@queue = :contact
	def self.perform (ad_id, current_id)
			user = User.find_by_id(current_id)
		    UserContact.connect(User.find_by_id(ad_id).email, user).deliver_now

	end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/material.rb
class Material < ActiveRecord::Base
	ratyrate_rateable 'rating'
	 validates :title,:semester,:branch,:subject,:category,:file, presence: true
	 
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   ratyrate_rater
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  has_many :questions
  has_many :answers
 

  mount_uploader :profile_pic, ProfilePicUploader 
      OPTIONS = [
        "CSE", "ECE","ICE","EEE","MECHANICAL","EE","IT"
      ]
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy, :contact]
  before_action :authenticate_user!, only: [:new ,:show]
  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
    @ad=Ad.new
  end

 def contact
    UserContact.connect(User.find_by_id(@ad.user_id).email, current_user).deliver_now
    redirect_to '/ads'
 end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    puts params
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to '/ad/index', notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:user_id, :title, :description, :contact, :college, :branch, :semester)
    end
end

app/controllers/forum_controller.rb
class ForumController < ApplicationController
  def index
    @questions = Question.all
    Question.includes(:users).all
  end

  def question
    content = params["question"]["content"]
    @new_ques = current_user.questions.create(:content => content)

    respond_to do |format|

      format.js{}

    end

  end

  def answer

    content = params["answer"]["content"]
    ques_id = params["answer"]["question_id"]
    current_user.answers.create(:content => content , :question_id => ques_id)
    redirect_to "/forum/answer/#{ques_id}"

  end

  def show_answer
    @question = Question.find(params[:id])
    @answers = @question.answers
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!
  def index
  	@user=User.new
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def remove_profile_pic
    current_user.remove_profile_pic!
    current_user.save
    redirect_to edit_user_registration_path
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/ad_helper.rb
module AdHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/ads/_form.html.erb
<div class="row">
  <%= form_for(@ad) do |f| %>

  <% if @ad.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

    <ul>
      <% @ad.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row" id="form">
    <div class="input-field col s12">
      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s6">
      <%= f.label :contact %><br>
      <%= f.text_field :contact %>
    </div>
    <div class="input-field col s6">
      <%= f.label :college %><br>
      <%= f.text_field :college %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s6">
      <%= f.label :branch %><br>
      <%= f.text_field :branch %>
    </div>
    <div class="input-field col s6">
      <%= f.label :semester %><br>
      <%= f.text_field :semester %>
    </div>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %>
  
  <div class="waves-effect waves-light btn">
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
  
  <% end %>
</div>

app/views/ads/edit.html.erb
<h1>Editing Ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<p id="notice"><%= notice %></p>
<% unless current_user%> 
  <h1>New Add</h1>
<%end%>
<%if current_user%>
<a class="waves-effect waves-light btn" href="#modal1" id="centre">New Ad</a>
<div id="modal1" class="modal">
  <div class="modal-content">
   <h2>New Material</h2>
   <div class="row">
  <%= form_for(@ad) do |f| %>

  <% if @ad.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

    <ul>
      <% @ad.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row" id="form">
    <div class="input-field col s12">
      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s6">
      <%= f.label :contact %><br>
      <%= f.text_field :contact %>
    </div>
    <div class="input-field col s6">
      <%= f.label :college %><br>
      <%= f.text_field :college %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s6">
      <%= f.label :branch %><br>
      <%= f.text_field :branch %>
    </div>
    <div class="input-field col s6">
      <%= f.label :semester %><br>
      <%= f.text_field :semester %>
    </div>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %>
  
  <div class="waves-effect waves-light btn">
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
  
  <% end %>
</div>




 </div>
</div>
<%end%>
<h2>All Ads</h2>


<% @ads.each do |ad| %>

<div class="row">
  <div class="col s9 ">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= ad.title %></span>
        <p><%= ad.description %></p>
        <p>Posted By : <%= User.find_by_id(ad.user_id).username %></p>
      </div>
      <div class="card-action">
        <%= link_to 'Show', ad %>
        <!--<a href="#">This is a link</a>-->
      </div>
    </div>
  </div>
</div>


<% end %>


<br>

app/views/ads/new.html.erb
<h1>New Ad</h1>

<%= render 'form' %>

<%= link_to 'Back', ads_path %>

app/views/ads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= User.find_by_id(@ad.user_id).username %>
</p>

<p>
  <strong>Title:</strong>
  <%= @ad.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ad.description %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @ad.contact %>
</p>

<p>
  <strong>College:</strong>
  <%= @ad.college %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @ad.branch %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @ad.semester %>
</p>

<!-- <a class="waves-effect waves-light btn" href="/contact"><i class="material-icons left">contacts</i>Contact</a> -->
<%= link_to "Contact", class: "waves-effect waves-light btn", controller: "ads", action: "contact",id: @ad %>


<!-- <%= link_to 'Edit', edit_ad_path(@ad) %> | -->
<%= link_to 'Back', ads_path %>