config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'forum/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :materials do
    collection do
      get :download
    end
  end

  get '/ad/index'
  get '/contact' => 'ads#contact'

  resources :ads
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'home#index'

  get '/material/questionpaper'
  get '/material/notes'
  get '/material/semnotes'

  post '/remove_profile_pic'=>'profile#remove_profile_pic'
  post 'forum/question'
  post 'forum/answer'
  get 'forum/answer/:id' => 'forum#show_answer'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  ratyrate_rateable 'rating'
  belongs_to :user

end

app/models/ad_contact_worker.rb
class AdContactWorker

	@queue = :contact
	def self.perform (ad_id, current_id)
			user = User.find_by_id(current_id)
		    UserContact.connect(User.find_by_id(ad_id).email, user).deliver_now

	end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/material.rb
class Material < ActiveRecord::Base
	ratyrate_rateable 'rating'
	 validates :title,:semester,:branch,:subject,:category,:file, presence: true
	 
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   ratyrate_rater
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  has_many :questions
  has_many :answers
 

  mount_uploader :profile_pic, ProfilePicUploader 
      OPTIONS = [
        "CSE", "ECE","ICE","EEE","MECHANICAL","EE","IT"
      ]
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy, :contact]
  before_action :authenticate_user!, only: [:new ,:show]
  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
    @ad=Ad.new
  end

 def contact
    UserContact.connect(User.find_by_id(@ad.user_id).email, current_user).deliver_now
    redirect_to '/ads'
 end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    puts params
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to '/ad/index', notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:user_id, :title, :description, :contact, :college, :branch, :semester)
    end
end

app/controllers/forum_controller.rb
class ForumController < ApplicationController
  def index
    @questions = Question.all
    Question.includes(:users).all
  end

  def question
    content = params["question"]["content"]
    @new_ques = current_user.questions.create(:content => content)

    respond_to do |format|

      format.js{}

    end

  end

  def answer

    content = params["answer"]["content"]
    ques_id = params["answer"]["question_id"]
    current_user.answers.create(:content => content , :question_id => ques_id)
    redirect_to "/forum/answer/#{ques_id}"

  end

  def show_answer
    @question = Question.find(params[:id])
    @answers = @question.answers
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!
  def index
  	@user=User.new
  end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/ad_helper.rb
module AdHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/forum/_answer.html.erb
<% str = "answer_modal_#{ques.id}" %>
<div id="<%= str %>" class="modal">
  <div class="modal-content">
    <h3><%= ques.content %></h3>
    <%= form_for :answer, url:forum_answer_path , method: :post do |f| %>
        <%= f.text_area :content,:placeholder =>"Write here...",:id=>"answer_content" %>
        <%= f.hidden_field :question_id,:value => ques.id %>
        <%= f.submit 'Answer' %>
    <% end %>
  </div>
</div>

app/views/forum/_question.html.erb
<div class="row">
  <div class="col s6 offset-s2">
    <div class="card-panel">
          <span>
            <%= ques.content %>
            <blockquote>
              asked by <%= ques.user.username %>
            </blockquote>
          </span>

          <% str = "#answer_modal_#{ques.id}" %>
          <%= link_to "Answer This question",str %>
          <%= link_to "View Answers","/forum/answer/#{ques.id}" %>
    </div>
  </div>
</div>

app/views/forum/index.html.erb
<div class="container">

  <%= form_for :question, url:forum_question_path, method: :post, remote: true do |f| %>
      <%= f.text_area :content,:id=>"question_content" %>
      <%= f.submit 'ASK' %>
  <% end %>

  <div id="questions">
    <% @questions.each do |q| %>
      <%= render 'question',:ques => q %>
      <%= render 'answer',:ques=>q %>

  <% end %>
  </div>


</div>

app/views/forum/question.js.erb
$("#questions").append("<%= escape_javascript(render 'question',:ques => @new_ques) %>");
$("#question_content").val("");

app/views/forum/show_answer.html.erb
<div class="container">

  <div class="row">
    <div class="col s6 offset-s2">
      <div class="question_details">
        <p><%= @question.content %></p>
        <% str = "#answer_modal_#{@question.id}" %>
        <a href ="<%= str %>" class="waves-effect waves-light btn answer_submit"><i class="fa fa-pencil" aria-hidden="true"></i>
          Answer</a>
        <%= render 'answer',:ques=>@question %>
      </div>
    </div>
  </div>


  <% @answers.each do |a| %>
    <div class="row">
      <div class="col s6 offset-s2">
        <div class="answer">
          <header>
            <%= image_tag a.user.profile_pic.thumb.url || ProfilePicUploader.default_url(:thumb) %>
            <div class="info">
              <% if a.user.first_name.length>0 %>
                  <div><%= "#{a.user.first_name} #{a.user.last_name}" %></div>
              <% else %>
                  <div><%= "#{a.user.username}" %></div>
              <% end %>
              <% if a.created_at == a.updated_at %>
                <div>Answered: <%= a.updated_at.strftime("%a, %B %d %Y %I:%M %P") %></div>
              <% else %>
                <div>Updated: <%= a.updated_at.strftime("%a, %B %d %Y %I:%M %P") %></div>
              <% end  %>
            </div>
          </header>

          <div class="answer_content">
            <%= a.content %>
          </div>

        </div>
      </div>
    </div>
  <% end %>


</div>

app/views/home/index.html.erb
<div id="index-banner" class="parallax-container" style="background: url(background.gif); background-size: cover;">
  <div class="section no-pad-bot" >
    <div class="container">
      <br><br>
      <h1 class="header center teal-text text-lighten-2">Project Name</h1>
      <div class="row center">
        <h5 class="header col s12 light white-text">A portal for all kinds of books, notes, question papers and more...</h5>
      </div>
      <div class="row center">
        <% if user_signed_in? %>
        <a class="waves-effect waves-light btn" id="centre">WELCOME, <%= current_user.username %></a>

        <% end %>
        <% unless user_signed_in? %>
        <!-- Modal Trigger -->
        <a class="waves-effect waves-light btn" href="#modal1" id="centre">Login</a>

        <!-- Modal Structure login-->
        <div id="modal1" class="modal">
          <div class="modal-content">
           <h2>Log in</h2>

           <%= form_for @user, :as => :user, :url => new_user_session_path(@user) do |f| %>
           <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true %>
          </div>

          <div class="field">
            <%= f.label :password %><br />
            <%= f.password_field :password, autocomplete: "off" %>
          </div>


          <div class="actions">
            <%= f.submit "Log in" %>
          </div>
          <% end %>
          <%= link_to "Forgot your password?", new_password_path(@user) %><br />
          <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(@user) %><br />

        </div>
        <% end %>

      </div>

    </div>
    <br><br>

  </div>
</div>
<!-- <div class="parallax"><img src="background1.jpg" alt="Unsplashed background img 1"></div> -->
</div>




<div class="container">
  <div class="section">

    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="medium material-icons ">shopping_cart</i></h2>
          <h5 class="center">College Store</h5>

          <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block ">
          <h2 class="center brown-text"><i class="medium material-icons ">forum</i></h2>
          <h5 class="center">Forum</h5>

          <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="medium material-icons">assignment</i></h2>
          <h5 class="center">Study Material</h5>

          <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
        </div>
      </div>
    </div>

  </div>
</div>



<footer class="page-footer teal">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Company Bio</h5>
        <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Settings</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
          <li><a class="white-text" href="#!">Link 3</a></li>
          <li><a class="white-text" href="#!">Link 4</a></li>
        </ul>
      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Connect</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
          <li><a class="white-text" href="#!">Link 3</a></li>
          <li><a class="white-text" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">

  </div>
</footer>