config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'forum/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :materials do
    collection do
      get :download
    end
  end

  get '/ad/index'
  get '/contact' => 'ads#contact'

  resources :ads
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'home#index'

  get '/material/questionpaper'
  get '/material/notes'
  get '/material/semnotes'

  post '/remove_profile_pic'=>'profile#remove_profile_pic'
  post 'forum/question'
  post 'forum/answer'
  get 'forum/answer/:id' => 'forum#show_answer'

end

app/models/material.rb
class Material < ActiveRecord::Base
	ratyrate_rateable 'rating'
	 validates :title,:semester,:branch,:subject,:category,:file, presence: true
	 
end

app/controllers/material_controller.rb
class MaterialController < ApplicationController

  def notes
  end


  def questionpaper
  end	

  def semnotes
 @branch=params[:data]
 puts @branch

  end


end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController

  before_action :set_material, only: [:show, :edit, :update, :destroy ,:download]
  before_action :authenticate_user!, only: [:edit, :update, :destroy,:new, :create]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
    @material=Material.new
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end


  def download
    puts params
    extension=@material.file.split('.')
    send_file Rails.root.join('public','uploadedfiles',@material.file),
    :type=>"application/#{extension[1]}", :x_sendfile=>true
  end


  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    puts params


    puts params
    #params.permit(:file,:semester, :branch, :subject, :category, :title)
    @material = Material.new(material_params)
    filename=params[:material][:file]
    File.open(Rails.root.join('public','uploadedfiles',filename.original_filename), 'wb') do |file|
      file.write(filename.read)
    end
    # uploaded_file = material_params[:file]
    # filepath = Dir.pwd + "/public/uploadedfiles/" + filename
    # File.open(filepath,'wb') do |file|
    #   file.write(uploaded_file.read())
    # end

    @material.file=filename.original_filename
    @material.user_id=current_user.id
    respond_to do |format|
      if @material.save
        Newcourse.detail(@material).deliver_later
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:semester, :branch, :subject, :category, :title, :file)
    end
  end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<!-- STATUS = [['Active', 'active'], ['In Active', 'inactive']] -->





<div class="row">
  <% if @material.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

    <ul>
      <% @material.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%= form_for(@material) do |f| %>
  <div class="row" id="form">
    <div class="input-field col s12">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label :subject %><br>
      <%= f.text_field :subject %>
    </div>
  </div>
  <div class="row" id="form">
    <!-- <div class="input-field col s6">
      <%= f.label :semester %><br>
      <%= f.text_field :semester %>
    </div> -->

    <%= f.select :semester, [["Semester", ""], ["First", 1], ["Second", 2], ["Third", 3], ["Fourth", 4], ["Fifth", 5], ["Sixth", 6], ["Seventh", 7], ["Eighth", 8]], {}, {class: "form-control"} %>
    <span>&nbsp; </span>
    <%= f.select :branch, [["Branch", ""], ["CSE", "CSE"], ["IT", "IT"], ["ECE", "ECE"], ["EEE", "EEE"], ["ICE", "ICE"]], {}, {class: "form-control"} %>
    <!-- <div class="input-field col s6">
      <%= f.label :branch %><br>
      <%= f.text_field :branch %>
    </div> -->
  </div>
  <div class="row">
    <div class="input-field col s12">

      <%= f.select :category, [["Category", ""], ["Notes", "Notes"], ["Question Paper", "Question Paper"], ["Books", "Books"]], {}, {class: "form-control"} %>
    </div>
  </div>




  
  <!-- <div class="waves-effect waves-light btn"> -->
  <!-- <div class="field"> -->
  <%= f.file_field :file %>
  <!-- </div> -->
  <!-- </div> -->
  <br>
  <br>
  <div class="waves-effect waves-light btn">
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
  <% end %>
</div>

app/views/materials/edit.html.erb
<h1>Editing Material</h1>

<%= render 'form' %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<p id="notice"><%= notice %></p>
<a class="waves-effect waves-light btn" href="#modal1" id="centre">New Material</a>
<div id="modal1" class="modal">
  <div class="modal-content">
   <h2>New Material</h2>
   <div class="row">
  <% if @material.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

    <ul>
      <% @material.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%= form_for(@material) do |f| %>
  <div class="row" id="form">
    <div class="input-field col s12">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label :subject %><br>
      <%= f.text_field :subject %>
    </div>
  </div>
  <div class="row" id="form">
    <!-- <div class="input-field col s6">
      <%= f.label :semester %><br>
      <%= f.text_field :semester %>
    </div> -->

    <%= f.select :semester, [["Semester", ""], ["First", 1], ["Second", 2], ["Third", 3], ["Fourth", 4], ["Fifth", 5], ["Sixth", 6], ["Seventh", 7], ["Eighth", 8]], {}, {class: "form-control"} %>
    <span>&nbsp; </span>
    <%= f.select :branch, [["Branch", ""], ["CSE", "CSE"], ["IT", "IT"], ["ECE", "ECE"], ["EEE", "EEE"], ["ICE", "ICE"]], {}, {class: "form-control"} %>
    <!-- <div class="input-field col s6">
      <%= f.label :branch %><br>
      <%= f.text_field :branch %>
    </div> -->
  </div>
  <div class="row">
    <div class="input-field col s12">

      <%= f.select :category, [["Category", ""], ["Notes", "Notes"], ["Question Paper", "Question Paper"], ["Books", "Books"]], {}, {class: "form-control"} %>
    </div>
  </div>




  
  <!-- <div class="waves-effect waves-light btn"> -->
  <!-- <div class="field"> -->
  <%= f.file_field :file %>
  <!-- </div> -->
  <!-- </div> -->
  <br>
  <br>
  <div class="waves-effect waves-light btn">
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
  <% end %>
</div>


 </div>
</div>

<!-- <table>
  <thead>
    <tr>
      <th>Semester</th>
      <th>Branch</th>
      <th>Subject</th>
      <th>Type</th>
      <th>Title</th>
      <th>AddedBy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.semester %></td>
        <td><%= material.branch %></td>
        <td><%= material.subject %></td>
        <td><%= material.category %></td>
        <td><%= material.title %></td>
        <td><%= material.user_id %></td>
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Download', download_materials_path(material,id:material.id) %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br> -->


<% @materials.each do |material| %>

<div class="row" id="materialcard">
  <div class="col s12">
    <div class="card #F5F2ED">
      <div class="card-content white-text">
        <div class="contentheader">      
          <span class="card-title"><%= material.subject %></span>
          <%unless current_user%>
          <span><%=link_to 'Rate This',new_user_session_path%></span>
          <%end%>
        </div>
        <h3>Added By:<%= material.user_id %></h3>
        <h3>Rating  : <%= rating_for material, 'rating',disable_after_rate: true, imdb_avg: true ,cancel_place: 'right',cancel_hint: 'Cancel this vote!',half_show: true%></h3>
        <div class="information">
          <div class="informationunit">
            <span class="heading">Title</span> 
            <span class="detailing"><%= material.title %></span>
          </div>
          <div class="informationunit">
            <span class="heading">Semester</span> 
            <span class="detailing"><%= material.semester %></span>
          </div>
          <div class="informationunit">
            <span class="heading">Branch</span> 
            <span class="detailing"><%= material.branch %></span>
          </div>
        </div>
      </div>
      <div class="card-action">
       <%= link_to 'Show', material %>
       <%= link_to 'Download', download_materials_path(material,id:material.id) %>
     </div>
   </div>
 </div>
</div>

<br>
<%end%>

app/views/materials/new.html.erb
<h1>New Material</h1>

<%= render 'form' %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Semester:</strong>
  <%= @material.semester %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @material.branch %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @material.subject %>
</p>

<p>
  <strong>Category:</strong>
  <%= @material.category %>
</p>

<p>
  <strong>Title:</strong>
  <%= @material.title %>
</p>

<p>
  <strong>AddedBy:</strong>
  <%= @material.user_id %>
</p>


<p>
  <strong>File:</strong>
  <iframe src="/uploadedfiles/<%= @material.file %>"> </iframe>
  
</p>

<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>
-->

<p id="notice"><%= notice %></p>

<div class="card" id="notescard">

  <div class="leftsideimage">
  </div>

  <div class="rightsideimage">
    <div class="card" id="subjectdetail">
      <div class="card-image waves-effect waves-block waves-light">
        <p>
          <strong>Semester:</strong>
          <%= @material.semester %>
        </p>

        <p>
          <strong>Branch:</strong>
          <%= @material.branch %>
        </p>

        <p>
          <strong>Subject:</strong>
          <%= @material.subject %>
        </p>

        <p>
          <strong>Category:</strong>
          <%= @material.category %>
        </p>

        <p>
          <strong>Title:</strong>
          <%= @material.title %>
        </p>

        <p>
          <strong>AddedBy:</strong>
          <%= @material.user_id %>
        </p>

      </div>
      <div class="card-content">
        <span class="card-title activator red-text text-darken-4">Preview</span>
        <p><%= link_to 'Edit', edit_material_path(@material) %></p>
        <p><%= link_to 'Back', materials_path %></p>
      </div>
      <div class="card-reveal">
        <span class="card-title grey-text text-darken-4">Notes Preview<i class="material-icons right">close</i></span>
        <p>
          <strong>File:</strong>
          <iframe src="/uploadedfiles/<%= @material.file %>" width="100%" height="500" > </iframe>

        </p>
      </div>
    </div>
  </div>
</div>