config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'forum/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :materials do
    collection do
      get :download
    end
  end

  get '/ad/index'
  get '/contact' => 'ads#contact'

  resources :ads
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'home#index'

  get '/material/questionpaper'
  get '/material/notes'
  get '/material/semnotes'

  post '/remove_profile_pic'=>'profile#remove_profile_pic'
  post 'forum/question'
  post 'forum/answer'
  get 'forum/answer/:id' => 'forum#show_answer'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  ratyrate_rateable 'rating'
  belongs_to :user

end

app/models/ad_contact_worker.rb
class AdContactWorker

	@queue = :contact
	def self.perform (ad_id, current_id)
			user = User.find_by_id(current_id)
		    UserContact.connect(User.find_by_id(ad_id).email, user).deliver_now

	end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/material.rb
class Material < ActiveRecord::Base
	ratyrate_rateable 'rating'
	 validates :title,:semester,:branch,:subject,:category,:file, presence: true
	 
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   ratyrate_rater
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  has_many :questions
  has_many :answers
 

  mount_uploader :profile_pic, ProfilePicUploader 
      OPTIONS = [
        "CSE", "ECE","ICE","EEE","MECHANICAL","EE","IT"
      ]
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy, :contact]
  before_action :authenticate_user!, only: [:new ,:show]
  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
    @ad=Ad.new
  end

 def contact
    UserContact.connect(User.find_by_id(@ad.user_id).email, current_user).deliver_now
    redirect_to '/ads'
 end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    puts params
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to '/ad/index', notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:user_id, :title, :description, :contact, :college, :branch, :semester)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!
  def index
  	@user=User.new
  end

end

app/helpers/ad_helper.rb
module AdHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>

  <%= javascript_include_tag 'application','jquery', 'data-turbolinks-track' => true  %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


</head>
<body>

  <% if notice %>
  <script type="text/javascript">
    Materialize.toast('<%= notice %>', 4000)
  </script>
  <% end %>
  <% if alert %>
  <script type="text/javascript">
    Materialize.toast('<%= alert %>', 4000)
  </script>
  <% end %>



  <nav>
    <div class="nav-wrapper light-blue darken-1">
      <a href="/" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to 'College Store', ads_path %></li>
        <li>
          <a class='dropdown-button ' href='#' data-activates='dropdown1'>Study Material</a>

          <!-- Dropdown Structure -->
          <ul id='dropdown1' class='dropdown-content'>
            <li><a href="#!">Books</a></li>
            <li><a href="/material/notes">Notes</a></li>
            <!--<li class="divider"></li>-->
            <li><a href="/material/questionpaper">Question Paper</a></li>
            <li><a href="#!">Video Links</a></li>
            <!--<li><a href="#!"><i class="material-icons">cloud</i>five</a></li>-->
          </ul>
        </li>
        <%unless user_signed_in? %>
        <li><%= link_to "Sign up", new_user_registration_path(@user) %></li>
        <%end%>
        <li><%= link_to "Forum",forum_index_path %></li>
        <% if user_signed_in? %>
        <li><a href="/users/edit">My Account</a></li>
        <% end %>
      </ul>
    </div>
  </nav>
  <!--<% if user_signed_in? %>-->
  <!--<%= link_to 'Logout', destroy_user_session_path, method: :delete %>-->
  <!--<% end %>-->

  <div class="fixed-action-btn">

    <% if user_signed_in? %>
    <%= link_to '<i class="material-icons">exit to app</i>', destroy_user_session_path, method: :delete, class: "btn-floating btn-large waves-effect waves-light red"  %>

    <% end %>


    <!--<a class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">input</i></a>-->
  </div>

  <%= yield %>

</body>
</html>

app/views/newcourse/detail.html.erb
<h1><%=@greeting%></h1>
<p>
	<%=@username%>
	This is a mail to inform you that a new <%=@subject%> , added to our website.Visit our website to review the
</p>
<p>
	To login to the site, just follow this link:
</p>
<p>Thanks for joining and have a great day!</p>

app/views/newcourse/detail.text.erb
Welcome to example.com, <%= @username %>
===============================================
 
You have successfully signed up to example.com,
your username is: <%= @username %>.
 
To login to the site, just follow this link:.
 
Thanks for joining and have a great day!

app/views/user_contact/connect.html.erb
<h4>Hey there! greetings from project_name,</h4>

<%=@customer.username%> showed in your add ad.<br>
Poke <%=@customer.username%> back to <%=@customer.email%> to make your deal